name: quran
description: Al-Qur'an app with minimum feature
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  cupertino_icons: ^1.0.2
  http: ^0.13.5
  sqflite: ^2.2.7
  shared_preferences: ^2.1.0
  infinite_scroll_pagination: ^3.2.0
  firebase_core: ^2.10.0
  firebase_app_check: ^0.1.2+2
  firebase_analytics: ^10.2.1

dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^2.0.0
#  change_app_package_name: ^1.1.0
#  flutter_launcher_icons: ^0.13.1
#  flutter_app_name: ^0.1.0

flutter:
  uses-material-design: true

#flutter_app_name:
#  name: "Al-Qur'an &amp; Terjemahan"

#flutter_launcher_icons:
#  android: false
#  ios: true
#  image_path: "android/app/src/main/ic_launcher-playstore.png"